simple_forest:
  bootstrap: true
  csv_seperator: ','
  data_filename: data.csv
  features_as_columns: true
  max_depth: 10
  max_features: sqrt
  max_samples: 0.75
  min_samples_leaf: 1
  min_samples_split: 2
  num_estimators_total: 100
  predicted_feature_name: Pyr
  random_state: 42
  sample_col: 0
  train_test_ratio: 1.0

