simple_forest:
  bootstrap: true
  csv_seperator: "\t"
  data_filename: full_corrected_data.csv
  features_as_columns: true
  max_depth: 10
  max_features: sqrt
  max_samples: 0.75
  min_samples_leaf: 1
  min_samples_split: 2
  num_estimators_total: 100
  predicted_feature_name: condition
  random_state: 47
  sample_col: 0
  train_test_ratio: 0.8
